import React, { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import {
  Box, Typography, Paper, Table, TableBody, TableCell,
  TableHead, TableRow, Button, TextField, Chip, CircularProgress,
  IconButton, MenuItem, Dialog, DialogTitle, DialogContent, DialogActions,
  ToggleButtonGroup, ToggleButton
} from '@mui/material';
import EditIcon from '@mui/icons-material/Edit';
import SaveIcon from '@mui/icons-material/Save';
import CancelIcon from '@mui/icons-material/Cancel';
import AddIcon from '@mui/icons-material/Add';
import { fetchProposedRules, updateProposedRule, createProposedRule } from '../../redux/slices/ruleBookSlice';

const BusinessRuleGenerator = () => {
  const dispatch = useDispatch();
  const { proposedRules, proposedRulesLoading } = useSelector(state => state.ruleBooks);

  const [editingId, setEditingId] = useState(null);
  const [editText, setEditText] = useState('');
  const [selectedConnector, setSelectedConnector] = useState('');
  const [updatingRuleId, setUpdatingRuleId] = useState(null);

  // Add rule modal state
  const [openAddModal, setOpenAddModal] = useState(false);
  const [newRuleType, setNewRuleType] = useState('custom_sql');
  const [newRuleText, setNewRuleText] = useState('');

  useEffect(() => {
    dispatch(fetchProposedRules());
  }, [dispatch]);

  // Extract unique connectors and set default
  const connectors = Array.from(new Set(proposedRules?.map(r => r.connector_name))).filter(Boolean);

  useEffect(() => {
    if (connectors.length > 0 && !selectedConnector) {
      setSelectedConnector(connectors[0]);
    }
  }, [connectors, selectedConnector]);

  // Helper to parse JSON formatted rules
  const parseRuleJson = (rawText) => {
    let name = '';
    let desc = rawText;
    
    if (rawText && rawText.startsWith('{')) {
      try {
        const parsed = JSON.parse(rawText);
        name = parsed.rule_name || '';
        desc = parsed.description || parsed.rule_text || rawText;
      } catch (e) {
        // Not JSON
      }
    }
    
    if (typeof desc === 'string') {
      desc = desc.replace(/[{}]/g, '').replace(/"/g, '');
    }
    return { name, desc };
  };

  const filteredRules = proposedRules?.filter(r => r.connector_name === selectedConnector) || [];
  const currentIndustryType = filteredRules.length > 0 ? filteredRules[0].industry_type : '';

  const handleEditClick = (rule) => {
    setEditingId(rule.id);
    setEditText(parseRuleJson(rule.rule_text).desc);
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setEditText('');
  };

  const handleSaveEdit = (id) => {
    const currentRule = proposedRules.find(r => r.id === id);
    if (!currentRule) return;
    dispatch(updateProposedRule({
      ruleId: id,
      ruleText: editText,
      statusId: currentRule.status_id
    }));
    setEditingId(null);
  };

  const handleStatusChange = async (rule, newStatusId) => {
    setUpdatingRuleId(rule.id);
    try {
      await dispatch(updateProposedRule({
        ruleId: rule.id,
        ruleText: rule.rule_text,
        statusId: newStatusId
      })).unwrap();
    } catch (e) {
      console.error("Failed to update status", e);
    } finally {
      setUpdatingRuleId(null);
    }
  };

  const getStatusColor = (statusName) => {
    switch (statusName?.toLowerCase()) {
      case 'pending': return 'warning';
      case 'approved': return 'success';
      case 'rejected': return 'error';
      default: return 'default';
    }
  };

  const handleAddSubmit = () => {
    if (!selectedConnector) return;
    const connectorRow = proposedRules.find(r => r.connector_name === selectedConnector);
    if (!connectorRow) return;

    dispatch(createProposedRule({
      connectorId: connectorRow.connector_id,
      ruleType: newRuleType,
      ruleText: newRuleText
    }));
    setOpenAddModal(false);
    setNewRuleType('custom_sql');
    setNewRuleText('');
  };

  return (
    <Box p={3}>
      <Typography variant="h4" gutterBottom>Proposed Business Rules (AI-Driven)</Typography>

      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="body1" color="textSecondary" paragraph>
          This section displays technical data quality rules automatically generated by the AI based on the industry context and database schema provided during connector creation.
          As a Business Analyst, you can review, edit, and approve these rules before they are enforced.
        </Typography>

        {proposedRulesLoading ? (
          <Box display="flex" justifyContent="center" p={4}>
            <CircularProgress />
          </Box>
        ) : proposedRules?.length === 0 ? (
          <Typography variant="body1" color="textSecondary">No proposed rules found. Please create a new connector with an Industry Context to generate rules.</Typography>
        ) : (
          <>
            <Box sx={{ mb: 3, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <Box sx={{ width: 300 }}>
                  <TextField
                    select
                    fullWidth
                    label="Select Connector"
                    value={selectedConnector}
                    onChange={(e) => setSelectedConnector(e.target.value)}
                    size="small"
                  >
                    {connectors.map(c => (
                      <MenuItem key={c} value={c}>{c}</MenuItem>
                    ))}
                  </TextField>
                </Box>
                {/* {currentIndustryType && (
                  <Chip label={`Industry: ${currentIndustryType}`} color="primary" variant="outlined" />
                )} */}
              </Box>

              <Button
                variant="contained"
                startIcon={<AddIcon />}
                onClick={() => setOpenAddModal(true)}
                disabled={!selectedConnector}
              >
                Add Rule
              </Button>
            </Box>

            <Table>
              <TableHead>
                <TableRow>
                  <TableCell width="15%">Category</TableCell>
                  <TableCell width="25%">Rule Name</TableCell>
                  <TableCell width="30%">Rule</TableCell>
                  <TableCell width="10%">Status</TableCell>
                  <TableCell width="20%">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {filteredRules.map(rule => (
                  <TableRow key={rule.id}>
                    <TableCell>
                      {rule.rule_type?.toLowerCase().includes('business') ? (
                        <Chip size="small" label="Business Rule" color="secondary" variant="outlined" sx={{ fontWeight: 'bold' }} />
                      ) : (
                        <Chip size="small" label="Technical Rule" color="primary" variant="outlined" sx={{ fontWeight: 'bold' }} />
                      )}
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" sx={{ fontWeight: 600 }}>
                        {parseRuleJson(rule.rule_text).name || rule.rule_type}
                      </Typography>
                    </TableCell>

                    <TableCell>
                      {editingId === rule.id ? (
                        <TextField
                          fullWidth
                          multiline
                          size="small"
                          value={editText}
                          onChange={(e) => setEditText(e.target.value)}
                        />
                      ) : (
                        <Typography variant="body2">{parseRuleJson(rule.rule_text).desc}</Typography>
                      )}
                    </TableCell>

                    <TableCell>
                      <Chip size="small" color={getStatusColor(rule.status_name)} label={rule.status_name || 'Unknown'} />
                    </TableCell>

                    <TableCell>
                      {editingId === rule.id ? (
                        <Box display="flex" gap={1}>
                          <IconButton size="small" color="primary" onClick={() => handleSaveEdit(rule.id)}>
                            <SaveIcon fontSize="small" />
                          </IconButton>
                          <IconButton size="small" color="default" onClick={handleCancelEdit}>
                            <CancelIcon fontSize="small" />
                          </IconButton>
                        </Box>
                      ) : (
                        <Box display="flex" gap={1} alignItems="center">
                          <IconButton size="small" onClick={() => handleEditClick(rule)} disabled={updatingRuleId === rule.id}>
                            <EditIcon fontSize="small" />
                          </IconButton>
                          {updatingRuleId === rule.id ? (
                            <CircularProgress size={24} sx={{ ml: 2 }} />
                          ) : (
                            <ToggleButtonGroup
                              value={rule.status_name?.toLowerCase()}
                              exclusive
                              onChange={(e, newVal) => {
                                if (newVal && newVal !== rule.status_name?.toLowerCase()) {
                                  if (newVal === 'approved') handleStatusChange(rule, 2);
                                  else if (newVal === 'rejected') handleStatusChange(rule, 3);
                                }
                              }}
                              size="small"
                              sx={{ ml: 1 }}
                            >
                              <ToggleButton value="approved" color="success">
                                Approve
                              </ToggleButton>
                              <ToggleButton value="rejected" color="error">
                                Reject
                              </ToggleButton>
                            </ToggleButtonGroup>
                          )}
                        </Box>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </>
        )}
      </Paper>

      {/* Add Rule Modal */}
      <Dialog open={openAddModal} onClose={() => setOpenAddModal(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Add Manual Business Rule</DialogTitle>
        <DialogContent dividers>
          <Box display="flex" flexDirection="column" gap={3} pt={1}>
            <TextField
              select
              label="Rule Type"
              value={newRuleType}
              onChange={(e) => setNewRuleType(e.target.value)}
              fullWidth
            >
              <MenuItem value="null_check">null_check</MenuItem>
              <MenuItem value="unique_check">unique_check</MenuItem>
              <MenuItem value="range_check">range_check</MenuItem>
              <MenuItem value="regex_check">regex_check</MenuItem>
              <MenuItem value="custom_sql">custom_sql</MenuItem>
              <MenuItem value="row_count_check">row_count_check</MenuItem>
            </TextField>
            <TextField
              label="Rule Logic (Text or SQL)"
              multiline
              rows={4}
              value={newRuleText}
              onChange={(e) => setNewRuleText(e.target.value)}
              fullWidth
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenAddModal(false)} color="inherit">Cancel</Button>
          <Button onClick={handleAddSubmit} variant="contained" disabled={!newRuleText}>Save Rule</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default BusinessRuleGenerator;
